### ISSUE TITLE
TypeScript Error on `application.start({ moduleName: "main-page" });`

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/template-hello-world-ng#1]
After cloning and running through the install instructions, the CLI is throwing the error...

    /Users/burkeholland/dev/nativescript/template-hello-world-ng/app/app.ts(2,1): error TS2346: Supplied parameters do not match any signature of call target.

Steps to reproduce...

1. Clone `template-hello-world-ng` into a new directory
2. `cd` into that directory
3. `npm install`
4. `tns platform add ios`
5. `tns run ios --emulator`

**Comment by aderbas** [comment]
+1 too

**Comment by tjvantoll** [comment]
@burkeholland @aderbas Can you try again. @hdeshev just pushed an update to Angular beta 1 and things are working for me.

**Comment by burkeholland** [comment]
Not seeing this error anymore. Got new ones. :)
