### ISSUE TITLE
Issue with tsconfig.json settings

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/template-hello-world-ng#12]
Hey all,

@burkeholland discovered an interesting issue today. This template does not include a `tsconfig.json` file, and because of that, a couple of important flags—most notably `"emitDecoratorMetadata"`—are not set, which causes some issues when you go to actually run an ng2 app.

Is there anyway we allow users to start ng2 apps with the appropriate flags set as expected?

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/nativescript-angular#191
