### ISSUE TITLE
Project can't be run

### ISSUE THREAD

**Issue by mrpatiwi** [NativeScript/template-hello-world-ng#2]
This project should be run with Grunt instead of `tns`.

**Errors:**
* [`gruntfile.js` at line 21](https://github.com/NativeScript/template-hello-world-ng/blob/master/gruntfile.js#L21) should be changed to an iOS device, like `iPhone 5`.
* `tsconfig.json` at [`ts:build`](https://github.com/NativeScript/template-hello-world-ng/blob/master/gruntfile.js#L26) has incorrect path. It should be `tsconfig: 'tsconfig.json'` instead of `tsconfig: 'app/tsconfig.json'`.
* Missing dev-dependencies: 
```json
    "grunt": "0.4.5",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-copy": "0.8.0",
    "grunt-shell": "1.1.2",
    "grunt-ts": "5.0.0-beta.5",
```
* Add to README.md commands: `grunt run-android`, `grunt run-geny` and `grunt run-ios`.

**Comment by hdeshev** [comment]
Hey @mrpatiwi 

That gruntfile is a remnant from the time when there was no typescript plugin, and the tns tool didn't support build hooks. I'd simply forgotten to delete the file.

If you need to integrate a tns build in a larger grunt-based build process, you can invoke `tns build <platform>` or `tns run <platform>` using a plugin like `grunt-shell`.
